export const PERSONAL_TASKS = [
    {
      id: 1,
      processName: "Produce MPEG",
      taskName: "Stich MPEG",
      priority: "Normal",
      jobNumber: 4520001,
      division: "South Carolina",
      childDivision: "",
      dateDime: "10/18/2021 9:00AM",
      thirdParty: "Third Party",
      client: "Kassel McVey",
      case: "Addison, Lavaunda Vs. South Carolina Dept Of Trans",
      primaryVendor: "Solange Ruiz-Uribe",
      deliveryMethod: "Expedited",
      deliveryDays: 3,
      jobDueDate: "10/21/2021",
      scheduleCity: "Columbia",
      proceedingType: "Depositions",
      assignedDate: "10/18/2021",
      litigationType: "Personal Injury/Negligence",
      taskDueDate: "10/21/2021",
      status: "Assigned",
    },
];

export const GROUP_TASKS = [
    {
      id: 1,
      processName: "Produce MPEG",
      taskName: "QC Original Files",
      priority: "Normal",
      jobNumber: 4544414,
      division: "Maryland",
      childDivision: "",
      dateDime: "10/18/2021 9:00 AM",
      thirdParty: "Third Party",
      client: "Litigation Services LLC",
      case: "Dorsey, Bessie Et Al. v. Lm General Insurance Company",
      primaryVendor: "Cappy Hallock",
      deliveryMethod: "Normal",
      deliveryDays: 10,
      jobDueDate: "10/21/2021",
      scheduleCity: "Baltimore",
      proceedingType: "Depositions",
      litigationType: "CR Referral",
      status: "Assgined",
      assignedDate: "10/18/2021",
      taskDueDate: "10/21/2021",
      assignedTo: "mdrenkalo",
    },
    {
      id: 2,
      processName: "Produce MPEG",
      taskName: "Review/ QC Files/ Prepare PIP Video",
      priority: "Urgent",
      jobNumber: 4572355,
      division: "Houston",
      childDivision: "",
      dateDime: "10/8/2021  1:00:00 PM",
      client: "Arnold & Itkin LLP",
      case: "In Re Brenn De Bree, Et Al.",
      primaryVendor: "Joanna Sagastisado",
      deliveryMethod: "Expedited",
      deliveryDays: 2,
      jobDueDate: "10/20/2021",
      scheduleCity: "Houston",
      proceedingType: "Depositions",
      litigationType: "Misc/Unknowns",
      status: "Overdue",
      assignedDate: "10/20/2021",
      taskDueDate: "10/20/2021",
      assignedTo: "dmcclutchy",
    },
    {
      id: 3,
      processName: "Produce MPEG",
      taskName: "Stich MPEG",
      priority: "High",
      jobNumber: 4520001,
      division: "South Carolina",
      childDivision: "",
      dateDime: "10/18/2021 9:00AM",
      thirdParty: "",
      client: "Kassel McVey",
      case: "Addison, Lavaunda Vs. South Carolina Dept Of Trans",
      primaryVendor: "Solange Ruiz-Uribe",
      deliveryMethod: "Expedited",
      deliveryDays: 3,
      jobDueDate: "10/21/2021",
      scheduleCity: "Columbia",
      proceedingType: "Depositions",
      assignedDate: "10/18/2021",
      litigationType: "Personal Injury/Negligence",
      taskDueDate: "10/21/2021",
      status: "New",
    },
    {
      id: 4,
      processName: "Produce MP4",
      taskName: "QC Files/ Prepare PIP Video/ Review",
      priority: "Urgent",
      jobNumber: 3490934,
      division: "Dallas",
      childDivision: "",
      dateDime: "10/8/2021  1:00:00 PM",
      client: "Garret and Shawn LLP",
      case: "In Re Brenn De Bree, Et Al.",
      primaryVendor: "Handerson Irias",
      deliveryMethod: "Expedited",
      deliveryDays: 2,
      jobDueDate: "10/20/2021",
      scheduleCity: "Dallas",
      proceedingType: "Depositions",
      litigationType: "Misc/Unknowns",
      status: "Overdue",
      assignedDate: "10/20/2021",
      taskDueDate: "10/20/2021",
      assignedTo: "gjames",
    },
];

export const TABLE_COLUMNS = [
    {
        field: "processName",
        headerName: "Process Name",
        width: 200,
        editable: false,
      },
      {
        field: "taskName",
        headerName: "Task Name",
        width: 200,
        editable: false,
      },
      {
        field: "priority",
        headerName: "Priority",
        width: 200,
        editable: false,
      },
      {
        field: "jobNumber",
        headerName: "Job Number",
        width: 200,
        editable: false,
      },
      {
        field: "division",
        headerName: "Division",
        width: 200,
      },
      {
        field: "childDivision",
        headerName: "Child Division",
        width: 200,
        editable: false,
      },
      {
        field: "dateDime",
        headerName: "Date/Time",
        width: 200,
        editable: false,
      },
      {
        field: "client",
        headerName: "Client",
        width: 200,
        editable: false,
      },
      {
        field: "thirdParty",
        headerName: "Third Party",
        width: 200,
        editable: false,
      },
      {
        field: "case",
        headerName: "Case",
        width: 200,
        editable: false,
      },
      {
        field: "primaryVendor",
        headerName: "Primary Vendor",
        width: 200,
        editable: false,
      },
      {
        field: "deliveryMethod",
        headerName: "Delivery Method",
        width: 200,
        editable: false,
      },
      {
        field: "deliveryDays",
        headerName: "Delivery Days",
        width: 200,
        editable: false,
      },
      {
        field: "jobDueDate",
        headerName: "Job Due Date",
        width: 200,
        editable: false,
      },
      {
        field: "scheduleCity",
        headerName: "Schedule City",
        width: 200,
        editable: false,
      },
      {
        field: "proceedingType",
        headerName: "Proceeding Type",
        width: 200,
        editable: false,
      },
      {
        field: "litigationType",
        headerName: "Litigation Type",
        width: 200,
        editable: false,
      },
      {
        field: "status",
        headerName: "Status",
        width: 200,
        editable: false,
      },
      {
        field: "assignedDate",
        headerName: "Assigned Date",
        width: 200,
        editable: false,
      },
      {
        field: "taskDueDate",
        headerName: "Task Due Date",
        width: 200,
        editable: false,
      },
];

  